# Generated by Django 4.0.6 on 2022-08-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('Gender', 'Gender'), ('male', 'male'), ('female', 'female')], default='Gender', max_length=10)),
                ('birth_date', models.DateField(default='1990-01-01')),
                ('image', models.ImageField(default='', upload_to='profile/')),
                ('bio', models.TextField(default='To change your bio, edit your profile!')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(default='', max_length=10)),
                ('last_name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='trips/')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.profile')),
            ],
        ),
    ]
