# Generated by Django 4.0.6 on 2022-08-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
