# Generated by Django 4.0.6 on 2022-08-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='want_to',
            field=models.ManyToManyField(blank=True, default=None, related_name='want_trips', to='trips.profile'),
        ),
    ]
