# Generated by Django 4.0.6 on 2022-08-02 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.profile'),
        ),
    ]
