# Generated by Django 4.0.6 on 2022-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_question_profile_my_questions_trip_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
