# Generated by Django 4.0.6 on 2022-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='To change your bio, edit your profile!'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://millingtontownship.com/wp-content/uploads/2021/01/default.jpg', upload_to='profile/'),
        ),
    ]
