# Generated by Django 4.0.6 on 2022-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_profile_bio_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=10),
        ),
    ]
