# Generated by Django 4.0.6 on 2022-08-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_question_profile_alter_question_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trips.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trips.profile'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trips.question'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.profile'),
        ),
    ]
