# Generated by Django 4.0.6 on 2022-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('male', 'male'), ('female', 'female')], default='Gender', max_length=10),
        ),
    ]
